### PR TITLE
Onefootball - Kotlin code challenge pull request 1.0.0

### PR DESCRIPTION
**Pull request by BlueTurtle7**
Hello Onefootball reviewers,

I am sending a Pull Request based on a feature branch called '**android-dev**'.
 
The changes I have made are as follows:

1. I applied a design pattern (MVP).
2. I added Dependency Injection to make it possible to test.
   2.1 If more Activities/Fragments are added there will be additional scopes, modules, components. 
3. I added a local DB based on realm.io
4. I mocked a network  Api behaviour, which returns an Observable<NewsApi> object- This is done in the data/helper package (Normally executed by the data/network which I left kind of stubbed).
5. I added a **BaseActivity** and a **BasePresenter**, in case new Activities shall be added. 
6. I saparated the Adapter from the Activity and binded it to the presenter as a data source.
7. Finally I tested the presenter.

Hopefully, this is more or less what was expected. If needed I will make additional changes :)

Thanks and enjoy reviewing

### CODE REVIEW

**Comment by BlueTurtle7** [comment]
PR opened locally as requested

**Comment by salih-gueler** [comment]
Hi @BlueTurtle7 

As stated in the README.md file, please create your repository as a **private** repository in your **own** account and create the PR there.

Thank you.

p.s. Please do not forget to update the reviewers by adding the teammates that is stated in the README.md file as collaborators.

**Comment by BlueTurtle7** [comment]
Hi Salih,

I have done that.

I have sent review requests to both you and Sebastian.

Thanks and best regards,
Eyal

**Comment by salih-gueler** [comment]
Hi Eyal,

With the emails that I received I only see a forked repository. Please update your project by pulling the remote changes before you submit and check out the documentation again.

Best,

Salih.

**Comment by BlueTurtle7** [comment]
Hi Salih,

There is a feature branch named android-dev in the repository, which
includes the commits.
Please check that one.

Best regards,
Eyal

**Pull request closed without merging**
