### PR TITLE
OneFootball Android Challenge - 1.0.0

### PR DESCRIPTION
**Pull request by mytemizer**
Hello reviewers,

All the insertions and suggestions to the project are explained below.

**_Code and architecture changes :_**

1- **MVVM** (Model - View - ViewModel) software design pattern is applied.
2- **Base Classes** are created in order to be able to insert Activities, Fragments, View Models and Repositories easily.
3- **Local Database** is created in order to be less-dependent to the outside (cloud or local json files). Room concept is used (explained in suggestion part).
4- **Utils and Enum** classes are added in order to make the code clear and easy to understand.
5- **Adapter** and **ViewHolder** are removed from Activity and created as classes and connected with related View Models.
6- **Live Data** are used in order to communicate between views and viewModels. 
7- **DataBinding** is used in order to get News' information and put it in the xml. This is used in order to make data up-to-date if data are converted to Live Data. Moreover, it removes the unnecessary accessing to the xml component from the code.
8- **Binding Adapter** is used in order to give custom attributes to the components in the xml file.

_**Suggestions for adding libraries and code snippets to code base (Gradle insertions):**_ 

1- **Room** -> Used in order to create abstraction layer over SQLite and make database accesses fluent. Moreover, compile-time verification of SQL queries is available in Room.
2- **LifeCycle** -> Base library for Mvvm architecture
3- **DataBinding** -> Used in order to create connection between View Models and xml files.
4- **Picasso** -> Loads image from URL.
5- **Gson** -> Easy to parse Json files.

Thanks for taking your time and reviewing.

### CODE REVIEW

**Comment by salih-gueler** [comment]
Hi @mytemizer 

As stated in the README.md file, please create your repository as a private repository in your own account and create the PR there.

Thank you.

p.s. Please do not forget to update the reviewers by adding the teammates that is stated in the README.md file as collaborators.

**Comment by mytemizer** [comment]
Hi Ms. Gueler,

Thanks for warning me. At first, I did it as in Readme.md. But then I saw
that other candidates forked and PRed your public repository. Therefore I
did it in that way too. I am going to fix it tonight.

Sincerely,

Muhammed Yusuf Temizer

**Comment by salih-gueler** [comment]
> Hi Ms. Gueler, Thanks for warning me. At first, I did it as in Readme.md. But then I saw that other candidates forked and PRed your public repository. Therefore I did it in that way too. I am going to fix it tonight. Sincerely, Muhammed Yusuf Temizer
> […](#)

All good, just check the README.md carefully and do not let the others influence you ;) 

p.s. it's Mr. Gueler or you can just call me Salih :)

**Comment by mytemizer** [comment]
Hi Salih,

Sorry for the typo :)

Have a good day

**Comment by mytemizer** [comment]
Hi Salih,

I have created the private repository and added 3 collaborators
(salih-gueler , katallaxie , damian-burke ) because github allows me to add
only 3 collaborators in private repositories since I have no premium
account. I also created PR to the repository. If you face any problem
please let me know.

Have a nice day,

Muhammed Yusuf Temizer

Salih Gueler <notifications@github.com>, 23 Eyl 2019 Pzt, 14:51 tarihinde
şunu yazdı:

**Pull request closed without merging**
